### ISSUE TITLE
Notes on the call to `mixIP`

### ISSUE THREAD

**Issue by ramanshah** [gaow/omics-bma#5]
Call graph for solving this problem via `mixIP`:

mixIP: R/mix_opt.R in ashr package

REBayes::KWDual: R/KWDual.R in REBayes package: dual optimization for
Kiefer-Wolfowitz problems

Rmosek::mosek: R/main.R in Rmosek package

.Call(mosek_sym, problem, opts): src/rmosek.cc in Rmosek package

**Comment by ramanshah** [comment]
My goal is to pull out the parameters and return value at each of these layers to assist in replicating the behavior in a Python implementation.

**Comment by ramanshah** [comment]
This seems like a weird thing to put into a codebase, so let me just attach it here, and you can decide if/where to commit it.

This is a debug trace where I run the R debugger through the execution of the above three functions running the code in `src/unit-tests/convex-op/CompareMixFit.R`. I inspect the parameters that each function receives and the value that each function returns. Since the test case is large, I just include the top and bottom parts of the 10000ish element arrays. I have a few comments enclosed in triple brackets `[[[ ... ]]]` so they're easy to pick out in an editor.

Hope this helps!
[notes.txt](https://github.com/gaow/omics-bma/files/67239/notes.txt)

**Comment by ramanshah** [comment]
A key observation is that the data matrix in `data.txt` is passed all the way down to the `mosek` call numerically unaltered.

**Comment by ramanshah** [comment]
Part of that fact is that the following in `mixIP`:

```
  A = rbind(diag(length(prior)),matrix_lik) # add in observations corresponding to prior
  w = c(prior-1,rep(1,n))
  A = A[w!=0,]    #remove zero weight entries, as these otherwise cause errors
  w = w[w!=0]
```

So the above statement will not be true if the prior is not `1 1 1`. When it is different from this value, the data will indeed be altered.

**Comment by gaow** [comment]
Here is the input data for the `mosek` function in R. [RmosekInput.txt](https://github.com/gaow/omics-bma/files/87946/RmosekInput.txt). The approach to take here is to construct the python version of the solver to have equivalent information as in this file and try it on the Python interface before integrating it formally to `omics-bma`

**Comment by gaow** [comment]
Seems my implementation (db4b824c91f0fc9c21b3da061715e3c0a5d340d9) works but does not give the correct result. Confused because I do not think I made any mistakes. Will keep this issue open and revisit later.

**Comment by gaow** [comment]
Thinking more into the optimization problem for mixture model I realize the output should be Lagrange multipliers for upper bounds on the constraints, rather than solution for the constraints. Fix was extremely easy and this issue is resolved.
